#!/usr/bin/env bash
set -euo pipefail

# Vaultec Production Deployment Installer
# Targets: Debian/Ubuntu Linux home servers (old laptop with docker-compose stack)
# Usage: sudo bash deploy/install.sh [--with-ai]

LOG_PREFIX="[vaultec-install]"

# Helper function for logging
log() {
    echo "$LOG_PREFIX $*"
}

log_info() {
    echo "$LOG_PREFIX [info] $*"
}

log_warn() {
    echo "$LOG_PREFIX [warn] $*"
}

log_error() {
    echo "$LOG_PREFIX [error] $*" >&2
}

# Check for Linux OS
log "Detecting operating system..."
if [[ ! "$OSTYPE" =~ ^linux ]]; then
    log_error "This script requires Linux. Detected OS: $OSTYPE"
    exit 1
fi
log_info "Detected Linux"

# Require root or sudo
log "Checking for root privileges..."
if [[ $EUID -ne 0 ]]; then
    log_info "Not running as root, re-executing with sudo..."
    exec sudo bash "$0" "$@"
fi
log_info "Running with root privileges"

# Move to repo root (script is at deploy/install.sh, so parent dir is repo root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
log "Moving to repo root: $REPO_ROOT"
cd "$REPO_ROOT"

# Check for Docker + compose plugin
log "Checking for Docker and docker-compose plugin..."
if ! command -v docker &> /dev/null; then
    log_warn "Docker not found, installing via official convenience script..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    bash /tmp/get-docker.sh
    log_info "Docker installed"

    # Enable docker service
    log "Enabling Docker service..."
    systemctl enable docker
    systemctl start docker
    log_info "Docker service enabled and started"
else
    log_info "Docker found: $(docker --version)"
fi

# Check for compose plugin
if ! docker compose version &> /dev/null; then
    log_error "docker-compose plugin not found after Docker install"
    exit 1
fi
log_info "docker-compose plugin available: $(docker compose version)"

# Generate .env if it doesn't exist
log "Checking for .env file..."
if [[ -f .env ]]; then
    log_info ".env already exists, skipping generation"
else
    log_info "Generating .env with secure defaults..."

    POSTGRES_USER="vaultec"
    POSTGRES_DB="vaultec"
    # Strong random password: 32 bytes base64
    POSTGRES_PASSWORD=$(openssl rand -base64 32)
    DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    VAULT_BLOB_DIR="/vault/blobs"
    VAULT_TMP_DIR="/vault/tmp"
    APP_ENV="prod"
    SESSION_COOKIE_NAME="vaultec_session"

    cat > .env << EOF
# Vaultec Production Environment
# Generated by deploy/install.sh

# Database
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}

# Vault paths (mount on LUKS-encrypted disk for production)
VAULT_BLOB_DIR=${VAULT_BLOB_DIR}
VAULT_TMP_DIR=${VAULT_TMP_DIR}

# Application
APP_ENV=${APP_ENV}
SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
EOF

    log_info ".env generated with secure password"
fi

# Build frontend SPA in a throwaway container (no Node on host required)
log "Building frontend SPA..."
if [[ ! -f frontend/build/index.html ]]; then
    log_info "Building frontend via docker container..."
    # Prefer reproducible `npm ci`, but fall back to `npm install` when the
    # lockfile has drifted out of sync with package.json (otherwise `npm ci`
    # aborts the whole install).
    docker run --rm \
        -v "$REPO_ROOT/frontend":/app \
        -w /app \
        node:20-alpine \
        sh -c "npm ci || npm install; npm run build"
    log_info "Frontend build complete"
else
    log_info "frontend/build/index.html already exists, skipping build"
fi

# Verify frontend build
if [[ ! -f frontend/build/index.html ]]; then
    log_error "Frontend build verification failed: frontend/build/index.html not found"
    exit 1
fi
log_info "Frontend build verified"

# Build docker images
log "Building docker images..."
docker compose build
log_info "Docker images built"

# Start core services (db, api, worker, caddy)
log "Starting core services (db, api, worker, caddy)..."
docker compose up -d db api worker caddy
log_info "Core services started"

# Optionally start ollama with AI models if --with-ai flag
if [[ "${1:-}" == "--with-ai" ]]; then
    log "Starting ollama service..."
    docker compose up -d ollama
    log_info "Ollama service started, pulling models..."

    # Pull small models (best effort, don't fail if this errors)
    log "Pulling qwen2.5:3b..."
    if docker compose exec -T ollama ollama pull qwen2.5:3b 2>/dev/null; then
        log_info "qwen2.5:3b pulled successfully"
    else
        log_warn "qwen2.5:3b pull failed (optional, continuing...)"
    fi

    log "Pulling nomic-embed-text..."
    if docker compose exec -T ollama ollama pull nomic-embed-text 2>/dev/null; then
        log_info "nomic-embed-text pulled successfully"
    else
        log_warn "nomic-embed-text pull failed (optional, continuing...)"
    fi
else
    log_info "Skipping ollama (use --with-ai to enable AI features)"
fi

# Wait for API health check (up to 60 seconds)
log "Waiting for API to become healthy (up to 60s)..."
MAX_ATTEMPTS=60
ATTEMPT=0
HEALTH_OK=false
while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
    if curl -sf http://localhost:8000/health &> /dev/null; then
        log_info "API is healthy"
        HEALTH_OK=true
        break
    fi
    ATTEMPT=$((ATTEMPT + 1))
    if [[ $((ATTEMPT % 10)) -eq 0 ]]; then
        log "Waiting... attempt $ATTEMPT/$MAX_ATTEMPTS"
    fi
    sleep 1
done

if [[ $HEALTH_OK == false ]]; then
    log_warn "API health check timed out (continuing anyway, check logs with 'docker compose logs api')"
fi

# Print next steps
log ""
log "=========================================="
log "  INSTALLATION COMPLETE"
log "=========================================="
log ""
log "NEXT STEPS:"
log ""
log "1. Get your server's IP address:"
log "   hostname -I"
log ""
log "2. Open in browser (accept self-signed certificate):"
log "   https://<server-ip>/"
log "   or"
log "   https://vaultec.local/"
log ""
log "3. On first run the vault is UNINITIALIZED. Easiest: open the UI and it will"
log "   send you to the setup wizard automatically. Create the admin account and the"
log "   master passphrase there."
log "   (Equivalent API call — note the exact field names:)"
log "   curl -k -X POST https://<server-ip>/setup \\"
log "     -H 'Content-Type: application/json' \\"
log "     -d '{\"passphrase\":\"<master-passphrase>\",\"admin_name\":\"admin\",\"admin_password\":\"<admin-pw>\"}'"
log ""
log "4. After every system reboot the vault is LOCKED. Unlock it (UI shows an Unlock"
log "   panel, or via API):"
log "   curl -k -X POST https://<server-ip>/unlock \\"
log "     -H 'Content-Type: application/json' \\"
log "     -d '{\"passphrase\":\"<master-passphrase>\"}'"
log ""
log "5. Data location (Docker volumes, recommend LUKS-encryption):"
log "   Database:   pgdata volume (contains PostgreSQL data)"
log "   Blobs:      vaultblobs volume (encrypted envelopes)"
log "   Temp:       vaulttmp volume"
log ""
log "6. View logs:"
log "   docker compose logs -f"
log ""
log "=========================================="
log ""

log "Install script complete!"
